runtime: python
env: flex

runtime_config:
    python_version: 3

entrypoint: streamlit run streamlit-Home.py --server.port $PORT

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
  target_concurrent_requests: 100